### ISSUE TITLE
ocaml 4.06.0+beta2

### ISSUE THREAD

**Issue by markghayden** [hcarty/proj4ml#4]
The setup.ml build script seems to not be updated for the new default safe strings.

best, Mark

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  ð
[proj4] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  ð
[ERROR] The compilation of proj4 failed at "ocaml setup.ml -configure --prefix /Users/mhayden/.opam/macos.dev".
Processing  1/1: [proj4: ocamlfind remove]
#=== ERROR while installing proj4.0.9.1 =======================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -configure --prefix /Users/mhayden/.opam/macos.dev
# path         /Users/mhayden/.opam/macos.dev/build/proj4.0.9.1
# compiler     4.06.0+beta2+flambda
# exit-code    2
# env-file     /Users/mhayden/.opam/macos.dev/build/proj4.0.9.1/proj4-16733-1872ec.env
# stdout-file  /Users/mhayden/.opam/macos.dev/build/proj4.0.9.1/proj4-16733-1872ec.out
# stderr-file  /Users/mhayden/.opam/macos.dev/build/proj4.0.9.1/proj4-16733-1872ec.err
### stderr ###
# File "./setup.ml", line 234, characters 8-26:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "./setup.ml", line 234, characters 8-11:
# Error: This expression has type string but an expression was expected of type
#          bytes

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  ð
The following actions failed
  â  install proj4 0.9.1
No changes have been performed

=-=- proj4.0.9.1 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  ð
=> This package relies on external (system) dependencies that may be missing. `opam depext proj4.0.9.1' may help you find the correct
   installation for your system.

**Comment by hcarty** [comment]
Thank you for the report! I'll try to get to this within the next week or so, probably by porting to jbuilder.

**Comment by whitequark** [comment]
@hcarty ping?

**Comment by markghayden** [comment]
Thanks!   I’m sorry for not getting back to you sooner.  I just noticed your email.

Please do not port to jbuilder, since we need proj4 to work with Whitequark’s cross-compilers (windows, IOS, and Android) and jbuilder apparently does not have cross-compiler support.

I think all that is required is re-creating the setup.ml with recent Oasis.

best, Mark

**Comment by hcarty** [comment]
Sorry for the delay - I'm unlikely to get a chance to fix this in the next few days.  If you can submit a PR I'll happily merge + tag a new release though.

**Comment by whitequark** [comment]
@hcarty Please run the following commands:
```
opam update oasis
sed -i -e s/0.9.1/0.9.2/ _oasis
oasis setup
git commit -m "Prepare for v0.9.2 release"
git tag v0.9.2
git push origin v0.9.2
git reset --hard origin/master
```
There is nothing to merge.

**Comment by hcarty** [comment]
I'm hoping to get to this this evening or over the weekend. Apologies for the delay - this isn't something I currently use for work or other active projects so it ends up getting bumped.

**Comment by hcarty** [comment]
@whitequark @markghayden Updated, tagged and pushed.  Tag `v0.9.2` builds for me now under 4.06.0.

Thank you for the report and sorry it took so long to update/fix.  If the tag works for you please close this issue!

**Comment by markghayden** [comment]
Seems to fix the issue.  BTW, how does this change get reflected in the main opam repository.

**Comment by hcarty** [comment]
I'll push out a release once I get a chance, hopefully in the next week or so. If someone else beats me to it that's ok too!

**Comment by markghayden** [comment]
Thanks!

**Comment by hcarty** [comment]
@markghayden https://github.com/ocaml/opam-repository/pull/10670 if all goes smoothly
