### ISSUE TITLE
opam build problem on MacOS / Xcode

### ISSUE THREAD

**Issue by markghayden** [hcarty/proj4ml#5]
On MacOS with Xcode 10.2 and apparently the gcc extension for labelling struct fields is generating a warning/error.

% opam install proj4
The following actions will be performed:
  - install proj4 0.9.2

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[proj4.0.9.2] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of proj4 failed at "/Users/mhayden/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -build".

#=== ERROR while compiling proj4.0.9.2 ========================================#
# context     2.0.3 | macos/x86_64 | ocaml-variants.4.07.1+macos10.11+flambda+no-flat-float-array | https://opam.ocaml.org/#c261c4ee
# path        ~/.opam/macos.dev/.opam-switch/build/proj4.0.9.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -build
# exit-code   1
# env-file    ~/.opam/log/proj4-31773-05296d.env
# output-file ~/.opam/log/proj4-31773-05296d.out
### output ###
# src/proj4_stubs.c:42:5: warning: use of GNU old-style field designator extension [-Wgnu-designator]
# [...]
# src/proj4_stubs.c:43:5: warning: use of GNU old-style field designator extension [-Wgnu-designator]
#     serialize: custom_serialize_default,
#     ^~~~~~~~~~
#     .serialize = 
# src/proj4_stubs.c:44:5: warning: use of GNU old-style field designator extension [-Wgnu-designator]
#     deserialize: custom_deserialize_default
#     ^~~~~~~~~~~~
#     .deserialize = 
# 6 warnings and 1 error generated.
# Command exited with code 2.
# E: Failure("Command ''/Users/mhayden/.opam/macos.dev/bin/ocamlbuild' src/libproj4_stubs.a src/dllproj4_stubs.so src/proj4.cma src/proj4.cmxa src/proj4.a src/proj4.cmxs -tag debug' terminated with error code 10")

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build proj4 0.9.2
+- 
- No changes have been performed
# Run eval `opam env` to update the current shell environment

**Comment by hcarty** [comment]
Thanks for reporting this!  I won't be able to work on this code for at least a few days.  I'll probably port the project to use dune at the same time.

If you have time to work on a patch I'd happily review + accept a PR!  Otherwise I'll try to get to this next week.

**Comment by markghayden** [comment]
Thanks for the quick response and maintaining this package.  I'm a bit slammed with other items, but will let you know if I have a chance to prepare a patch.

**Comment by markghayden** [comment]
Hezekiah,

FYI, I caught up with my other items and last week made a push request that addressed this

thanks, Mark

**Comment by hcarty** [comment]
Merged #6 which should fix this - please reopen if there are still issues!

**Comment by markghayden** [comment]
Thanks for merging this.  Can you also post a new opam version that includes the change?
